language: node_js

node_js:
  - "10.6.0" # current
  - "8.0" # stable
script:
  - "npm test"
# notifications:
#  irc:
#    channels:
#      - "irc.freenode.org#moutjs"
#    on_success: change
#    on_failure: always
#    use_notice: true
#    skip_join: true
# git:
#   depth: 10